### ISSUE TITLE
Test runner build broken

### ISSUE THREAD

**Issue by 5forcegees** [tgross/workshop-autopilot#23]
I'm doing research for a project where this approach might be a good fit. 

When building the tests image there are a variety of errors (though I might need to pass more in the command)
$HOME/code/workshop/tests
docker build -t tests .
...
Step 2:
...
Reading package lists...
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_fkrull_deadsnakes_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 20477 20487
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_restricted_binary-amd64_Packages.gz is not what the server reported 20387 23448
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-security_restricted_binary-amd64_Packages.gz is not what the server reported 17042 20231
...
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main ca-certificates all 20160104ubuntu0.14.04.1 [190 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
...
Setting up apparmor (2.8.95~2430-0ubuntu5.3) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
invoke-rc.d: policy-rc.d denied execution of start.
invoke-rc.d: policy-rc.d denied execution of reload.
... more like those
Step 4 :
  Failed building wheel for PyYAML
  Failed building wheel for MarkupSafe

Looks like there haven't been any updates to the repo in a couple months.  Is this something that is still in development?

**Comment by tgross** [comment]
Just FYI, you should be using the makefile to build this and the tests. `make build` will build the images. `make test-runner` will build the test runner.

It looks like the test runner build is broken though; it worked the last I checked on it but we don't have a continuous integration for this. Here's the full output of build I just did: https://gist.github.com/tgross/ba952f886ab51924d5e8be3f6aa9d8e4. It looks like the `MarkupSafe` and `PyYAML` wheels aren't building correctly. They may have changed upstream and we'll have to investigate what's up (although in the meantime, PRs welcome! 😀 )

> Looks like there haven't been any updates to the repo in a couple months. Is this something that is still in development?

It's in maintenance (until otherwise marked) but isn't under active development.

**Comment by tgross** [comment]
cc @geek any thoughts on whether the 3.x release should have fixed this?

**Comment by geek** [comment]
Building the test-runner image works...

```
Successfully built
```
